from fpdf import FPDF
import os

def create_pdf_report(image_path, heatmap_path, results, info, doctors_list, location):
    pdf = FPDF()
    pdf.add_page()
    
    pdf.set_font("Arial", size=16, style='B')
    pdf.cell(200, 10, txt="Skin Care AI Analytics Report", ln=True, align='C')
    pdf.ln(10)
    
    y_before_img = pdf.get_y()
    if os.path.exists(image_path):
        pdf.image(image_path, x=20, y=y_before_img, w=70)
    if heatmap_path and os.path.exists(heatmap_path):
        pdf.image(heatmap_path, x=110, y=y_before_img, w=70)
    
    pdf.set_y(y_before_img + 80)
    
    pdf.set_font("Arial", size=14, style='B')
    pdf.cell(200, 10, txt="Analysis Results", ln=True)
    
    pdf.set_font("Arial", size=12)
    # Using encode decode to strip out non-latin-1 characters like Hindi text
    safe_name = info['name'].encode('latin-1', 'replace').decode('latin-1')
    safe_severity = info['severity'].encode('latin-1', 'replace').decode('latin-1')
    safe_risk = info['risk_level'].encode('latin-1', 'replace').decode('latin-1')
    
    pdf.cell(200, 8, txt=f"Predicted Condition: {safe_name}", ln=True)
    pdf.cell(200, 8, txt=f"Confidence: {results[0]['confidence']:.1f}%", ln=True)
    pdf.cell(200, 8, txt=f"Severity: {safe_severity}", ln=True)
    pdf.cell(200, 8, txt=f"Risk Level: {safe_risk}", ln=True)
    pdf.ln(5)
    
    pdf.set_font("Arial", size=12, style='B')
    pdf.cell(200, 8, txt="Recommended Precautions:", ln=True)
    pdf.set_font("Arial", size=11)
    
    for prec in info['precautions']:
        safe_prec = prec.encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 8, txt=f"- {safe_prec}")
    
    pdf.ln(5)
    pdf.set_font("Arial", size=12, style='B')
    pdf.cell(200, 8, txt=f"Nearby Clinics ({location}):", ln=True)
    pdf.set_font("Arial", size=11)
    
    for doc in doctors_list:
        pdf.cell(200, 8, txt=f"{doc['name']} - {doc['distance_km']} km away ({doc['rating']} Stars)", ln=True)
        pdf.cell(200, 6, txt=f"Address: {doc['address']}", ln=True)
        pdf.ln(2)
        
    pdf.ln(5)
    pdf.set_font("Arial", size=10, style='I')
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 6, txt="Disclaimer: This report is generated by an AI model. It does not replace a professional medical diagnosis.")
    
    out_path = "medical_report.pdf"
    pdf.output(out_path)
    return out_path
